# Generated by Django 3.2.9 on 2022-01-05 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(default=0)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.supplier')),
            ],
            options={
                'verbose_name_plural': 'Articles',
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('reference', models.CharField(help_text='Almacen.', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'BranchOffices',
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(help_text='Código de Socio')),
                ('reference', models.CharField(help_text='Almacen.', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'unique_together': {('code',)},
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(help_text='Almacen.', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Distributions',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('generated_date', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se generó el pedido.')),
                ('amount', models.IntegerField(help_text='Cantidad solicitada.')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.branch')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.customer')),
                ('distribution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.distribution')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.article')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assorted_date', models.DateTimeField(help_text='Fecha y hora en que se surtió el pedido.')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.orderdetail')),
            ],
        ),
    ]
