# Generated by Django 3.2.9 on 2022-01-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Razón social.', max_length=100, null=True)),
                ('address', models.CharField(help_text='Dirección', max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('client_type', models.CharField(choices=[('01', 'NORMAL'), ('02', 'PLATA'), ('03', 'ORO'), ('04', 'PLATINO')], default='01', help_text='Catalogo tipos de cliente.', max_length=2)),
                ('name', models.CharField(help_text='Razón social.', max_length=100, null=True)),
                ('rfc', models.CharField(help_text='Registro federal de contribuyentes.', max_length=13)),
                ('logo', models.ImageField(help_text='Ruta imagen.', null=True, upload_to='')),
                ('address', models.CharField(help_text='Dirección', max_length=300, null=True)),
            ],
            options={
                'verbose_name_plural': 'Customers',
                'unique_together': {('code',)},
            },
        ),
    ]
